repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: no-commit-to-branch
  - repo: local
    hooks:
      - id: mix-test
        name: 'elixir: mix test'
        entry: mix test
        language: system
        pass_filenames: false
        files: \.exs*$
